### ISSUE TITLE
TODO in new_booking_process.php

### ISSUE THREAD

**Issue by miyurusankalpa** [miyurusankalpa/driver-booking#14]
- [x]  add json type header
- [x]  use mysqli_real_escape_string
- [x]  remove password encryption line
- [x]  fix the dash in arraypush line 25
- [x]  fix extra end bracket at line 32
- [x]  remodel the array and the output like in register_process.php
